version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: studentorg_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  backend:
    image: node:20-alpine
    container_name: studentorg_backend
    working_dir: /app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/studentorg
    volumes:
      - ./Backend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    image: node:20-alpine
    container_name: studentorg_frontend
    working_dir: /app
    environment:
      # Browser will call the backend through the host-mapped port
      - VITE_API_URL=http://localhost:3000/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data:
    driver: local


